### ISSUE TITLE
Lock "copy password" button.

### ISSUE THREAD

**Issue by diegocanton** [gopasspw/gopassbridge#121]
It would be interesting that GoPassBridge did not allow copying of the password, thinking of using teams.

A "team member" never having permission to view the password is useful for better access control.

GoPassBridge could only act as a facilitator, automatically fill in the fields and login. A "team member" would have the facility of logging in but never copying or viewing the password.

When there is a possibility of members being fired, there is always a risk of copying passwords and this is not something desired.
Viewing or copying passwords also makes sharing on other media easy, which reduces the functionality of a "password manager" when thinking about teams.

Sorry if this is already possible, unfortunately I found nothing that allows this block.
Translated Message: May contain errors or be difficult to understand.

**Comment by Pharb** [comment]
Hallo @diegocanton,

Because GoPassBridge is only a frontend/UI for gopass, there is no additional security benefit in hiding or disabling "Copy Password" here.
What ever you do, using shared team passwords there will always be the problem that team members can keep these passwords when leaving the team.

Basically to solve this you need one of these options:
- Do not use shared passwords. When each team member has their own, individual, secret password, then it is enough to revoke their accounts server-side, by deleting or disabling their user accounts.
- The only way when using shared passwords is to remove them from the password manager when they leave and afterwards change ALL shared passwords.

There is nothing else we could do in gopass or GoPassBridge to resolve this organisational problem for you.

Please also note that removing the gopass recipient and re-encrypting all passwords still does not solve this problem, because any recipient could have easily made a copy at any time in the past or they could recover the passwords from the git history.

**Comment by diegocanton** [comment]
Thank you very much gentlemen, after almost a week analyzing the options, I am believing that my need will only be solved with the internal development of a new type of solution. 

After sending this message I thought about this shared file problem, but the idea was that the operator would not have contact with this configuration of their terminal, being IT's responsibility, this would reduce but not solve the problem. 

I appreciate your help.
;)
