### ISSUE TITLE
Shortcut does not work when focused on a text input

### ISSUE THREAD

**Issue by lewisdiamond** [gopasspw/gopassbridge#124]
When loading a login page, the focus is usually on the text input component. When that happens, `Ctrl+Shift+u` does not load the gopass window.

**Comment by martinhoefling** [comment]
Which browser (version) and plugin version as well as platform is it?

**Comment by martinhoefling** [comment]
@lewisdiamond , I cannot reproduce this issue on my Mac, latest FFX and Chrome. `Command + Shift  + U` open the  gopassbridge popup.

**Comment by bascht** [comment]
@martinhoefling Can reproduce it on Linux – I guess @lewisdiamond is running into the same thing: 

`<Ctrl>+<Shift>+u` is bound to the Unicode input via ibus. And this shortcut [is not remappable](https://gitlab.gnome.org/GNOME/gtk/issues/171).

As @lewisdiamond said: It works if no text input field is focused, otherwise it will prompt for an unicode id:

![recording](https://user-images.githubusercontent.com/51264/65895707-2bc93f00-e3ac-11e9-9777-c26ff49274a8.gif)
Is there a way to remap the shortcut for gopassbridge?

**Comment by martinhoefling** [comment]
On firefox, you can change the shortcut via "manage extension shortcut" in the extension menu. In chrome under "keyboard shortcuts" in the hamburger menu in extensions. Does that help? We're just providing a default here and I would avoid to break that one.

**Comment by bascht** [comment]
Ha! Learned something today! I think that totally works as an alternative. Would be great if it where documented somewhere. Should I add a PR for a small section in the `README.md`?

**Comment by martinhoefling** [comment]
Sure! You can refer that issue here. I will keep it open then.

**Comment by bascht** [comment]
Oh geez. Had this in my backlog for quite a while. @martinhoefling thanks for adding it to the docs! :smiley_cat:
