### ISSUE TITLE
Project status for gopassbridge?

### ISSUE THREAD

**Issue by EvanCarroll** [gopasspw/gopassbridge#240]
It's been more than a year since last commit. Is this project still maintained? Many of the issues don't have any activity and many of the PRs don't have any input.

Also, I'm confused as to the _why_ here. Gopass says it's API compatible with pass.  The pass extension for the browser is called browserpass, which seems to be more active

* https://github.com/browserpass/browserpass-extension
* https://github.com/browserpass/browserpass-native

What advantages does this project have from browserpass? (I'm ignorant just asking).

**Comment by Pharb** [comment]
Thank you @EvanCarroll for the question.

Gopass is a non-commercial, open-source, actively developed, community driven project.

Gopassbridge is a small subproject, which I would consider maintained, but for some time there is little to no active feature development ongoing (e.g. all currently open PRs are failing CI checks, so I hope it is understandable that there is no input from core maintainers). Also anyone is encouraged to provide community support and bugfixes.

A healthy open-source ecosystem allows for alternative solutions, forking of projects, permissive licensing but also compatibility with existing tools like git/gpg/pass.

Personally I use gopass and gopassbridge on a daily basis and know several others who do. It works. It is supported. There are no known security issues. If it breaks tomorrow, I would be providing a bugfix as fast as possible because I use it for my daily work. There is no guarantee that this will not change at any point in the future, but this has been true for at least 5 years.

I would also like to point out that the latest version released in Chrome/Firefox stores of gopassbridge is newer than the browserpass-extension.

**Comment by EvanCarroll** [comment]
why would the release in the stores be newer then the release on gh?

**Comment by Pharb** [comment]
The gopassbridge version in the stores is the same as on GitHub: [v0.9.0](https://github.com/gopasspw/gopassbridge/releases/tag/v0.9.0)
