### ISSUE TITLE
Configurable hotkey? (Ctrl+Shift+U conflicts with unicode character inputs)

### ISSUE THREAD

**Issue by jcmuller** [gopasspw/gopassbridge#85]
The current hotkey (Control + Shift + U) is the global hotkey to allow typing Unicode characters. Hence, if you're on any input field, the field will swallow the keybinding. I have to always click out of the user name/password fields to be able to use the keybinding.

Is it possible to either change it (and possibly match browserpass' Ctrl-Shift-L), or make it configurable?

**Comment by martinhoefling** [comment]
In chrome, you can do so via chrome://extensions/configureCommands but not in Firefox https://support.mozilla.org/en-US/questions/1200032. I am not aware of a method to specify or select multiple combinations for the extension. One option would be to edit the manifest and rebuild the extension but that requires probably quite some effort and doesn't work for firefox anymore.

**Comment by jcmuller** [comment]
Some extensions (1Password X's comes to mind) have the ability to let the user specify what keybinding to use:

![image](https://user-images.githubusercontent.com/208500/46431608-3fe74b80-c71a-11e8-903e-5a5cf4cd5161.png)

**Comment by Pharb** [comment]
@jcmuller Thanks for bringing this to our attention. Generally I'm in favour of supporting as many common workflows as we can.

I certainly agree that this would be possible to implement, as other extensions have demonstrated, but I doubt that it would be as simple as just using the standard APIs that Chrome and Firefox provide for WebExtensions.

So considering prioritisation and the available development resources of current maintainers, I think we would just wait for it to be implemented in Firefox natively. The Firefox implementation is in progress and is currently being reviewed: https://bugzilla.mozilla.org/show_bug.cgi?id=1303384

Otherwise contributions are always welcome and if anyone has a robust and simple way to implement this enhancement, I would be available to discussion and review the implementation.

For now I also consider this "Won't fix" from my side.
