### ISSUE TITLE
loading infinitely

### ISSUE THREAD

**Issue by shibumi** [gopasspw/gopassbridge#96]
The gopass bridge is just loading infinitely with  Chromium | 71.0.3578.98 (Official Build) Arch Linux (64-bit)
![](https://paste.xinu.at/YmoAUD/)

**Comment by iicurtis** [comment]
Check your memory. I would bet it is consuming multiple gigabytes. That's what happened to me.

The fix for was that I hadn't properly installed/setup the bridge. Please follow the directions [here](https://github.com/gopasspw/gopass/blob/master/docs/setup.md#filling-in-passwords-from-browser).

Primarily all you need to do is run:
```
gopass jsonapi configure
```

**Comment by martinhoefling** [comment]
Did you properly install the gopass native messaging extension via `gopass jsonapi configure`? Have you checked that the paths there are the correct ones for Arch?

**Comment by shibumi** [comment]
@martinhoefling nevermind.. i am stupid. You are correct, i didn't follow your setup guide. Btw it would be nice if you could mention `jsonapi` as parameter in `gopass --help`. I would be willing to open a PR for this with a patch :) or is there  a reason why you don't mention it in `--help`?

**Comment by martinhoefling** [comment]
@shibumi I think it's ok to mention it. If you prepare a PR for gopass, that would be great. "Stupid" is also quite relative, takeaway for gopassbridge is that we should add an appropriate error message. Thx for raising this.
